site:
  name: Raido
  site: 'https://raido-website.netlify.app/'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: Raido
    template: '%s — Raido'
  description: 'Raido unterstützt Unternehmen mit Führung, Managementprozessen und Coaching für klare Entscheidungen, wirksame Strukturen und nachhaltigen Erfolg.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Raido
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website

i18n:
  language: de
  textDirection: ltr

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
